project:
  type: default

format:
  pdf:
    documentclass: article
    papersize: a4
    fontsize: 11pt
    toc: true
    number-sections: true
    geometry:
      - margin=2.5cm

execute:
  echo: false
  warning: false
  message: false
